// TradingEconomics labels FX pairs as bare 6-letter codes (EURUSD, USDJPY,
// ...), which is fine for traders but not very readable. This maps each
// 3-letter currency code to a plain-English name so pairs can be shown as
// "Euro - US Dollar" instead. Codes follow ISO 4217 except where noted
// (TradingEconomics uses a few of its own, e.g. "URY" for the Uruguayan
// Peso instead of the official "UYU", and "ZIG" for Zimbabwe's 2024
// gold-backed currency).
export const CURRENCY_NAMES: Record<string, string> = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  AUD: "Australian Dollar",
  NZD: "New Zealand Dollar",
  JPY: "Japanese Yen",
  CNY: "Chinese Yuan",
  CHF: "Swiss Franc",
  CAD: "Canadian Dollar",
  AED: "UAE Dirham",
  AFN: "Afghan Afghani",
  ALL: "Albanian Lek",
  AMD: "Armenian Dram",
  AOA: "Angolan Kwanza",
  ARS: "Argentine Peso",
  AZN: "Azerbaijani Manat",
  BAM: "Bosnia-Herzegovina Convertible Mark",
  BDT: "Bangladeshi Taka",
  BHD: "Bahraini Dinar",
  BIF: "Burundian Franc",
  BND: "Brunei Dollar",
  BOB: "Bolivian Boliviano",
  BRL: "Brazilian Real",
  BSD: "Bahamian Dollar",
  BWP: "Botswanan Pula",
  BYR: "Belarusian Ruble",
  CDF: "Congolese Franc",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  CRC: "Costa Rican Colon",
  CUC: "Cuban Convertible Peso",
  CVE: "Cape Verdean Escudo",
  CZK: "Czech Koruna",
  DJF: "Djiboutian Franc",
  DKK: "Danish Krone",
  DOP: "Dominican Peso",
  DZD: "Algerian Dinar",
  EGP: "Egyptian Pound",
  ERN: "Eritrean Nakfa",
  ETB: "Ethiopian Birr",
  FJD: "Fijian Dollar",
  GEL: "Georgian Lari",
  GHS: "Ghanaian Cedi",
  GMD: "Gambian Dalasi",
  GNF: "Guinean Franc",
  GTQ: "Guatemalan Quetzal",
  GYD: "Guyanaese Dollar",
  HKD: "Hong Kong Dollar",
  HNL: "Honduran Lempira",
  HTG: "Haitian Gourde",
  HUF: "Hungarian Forint",
  IDR: "Indonesian Rupiah",
  ILS: "Israeli Shekel",
  INR: "Indian Rupee",
  IQD: "Iraqi Dinar",
  IRR: "Iranian Rial",
  ISK: "Icelandic Krona",
  JMD: "Jamaican Dollar",
  JOD: "Jordanian Dinar",
  KES: "Kenyan Shilling",
  KGS: "Kyrgystani Som",
  KHR: "Cambodian Riel",
  KMF: "Comorian Franc",
  KPW: "North Korean Won",
  KRW: "South Korean Won",
  KWD: "Kuwaiti Dinar",
  KYD: "Cayman Islands Dollar",
  KZT: "Kazakhstani Tenge",
  LAK: "Laotian Kip",
  LBP: "Lebanese Pound",
  LKR: "Sri Lankan Rupee",
  LRD: "Liberian Dollar",
  LSL: "Lesotho Loti",
  LYD: "Libyan Dinar",
  MAD: "Moroccan Dirham",
  MDL: "Moldovan Leu",
  MGA: "Malagasy Ariary",
  MKD: "Macedonian Denar",
  MMK: "Myanma Kyat",
  MNT: "Mongolian Tugrik",
  MOP: "Macanese Pataca",
  MRO: "Mauritanian Ouguiya",
  MUR: "Mauritian Rupee",
  MVR: "Maldivian Rufiyaa",
  MWK: "Malawian Kwacha",
  MXN: "Mexican Peso",
  MYR: "Malaysian Ringgit",
  MZN: "Mozambican Metical",
  NAD: "Namibian Dollar",
  NGN: "Nigerian Naira",
  NIO: "Nicaraguan Cordoba",
  NOK: "Norwegian Krone",
  NPR: "Nepalese Rupee",
  OMR: "Omani Rial",
  PAB: "Panamanian Balboa",
  PEN: "Peruvian Sol",
  PGK: "Papua New Guinean Kina",
  PHP: "Philippine Peso",
  PKR: "Pakistani Rupee",
  PLN: "Polish Zloty",
  PYG: "Paraguayan Guarani",
  QAR: "Qatari Rial",
  RON: "Romanian Leu",
  RSD: "Serbian Dinar",
  RUB: "Russian Ruble",
  RWF: "Rwandan Franc",
  SAR: "Saudi Riyal",
  SCR: "Seychellois Rupee",
  SDG: "Sudanese Pound",
  SEK: "Swedish Krona",
  SGD: "Singapore Dollar",
  SLL: "Sierra Leonean Leone",
  SOS: "Somali Shilling",
  SRD: "Surinamese Dollar",
  SSP: "South Sudanese Pound",
  STD: "Sao Tomean Dobra",
  SVC: "Salvadoran Colon",
  SYP: "Syrian Pound",
  SZL: "Swazi Lilangeni",
  THB: "Thai Baht",
  TJS: "Tajikistani Somoni",
  TMT: "Turkmenistani Manat",
  TND: "Tunisian Dinar",
  TRY: "Turkish Lira",
  TTD: "Trinidad and Tobago Dollar",
  TWD: "New Taiwan Dollar",
  TZS: "Tanzanian Shilling",
  UAH: "Ukrainian Hryvnia",
  UGX: "Ugandan Shilling",
  URY: "Uruguayan Peso",
  UZS: "Uzbekistan Som",
  VES: "Venezuelan Bolivar",
  VND: "Vietnamese Dong",
  XAF: "Central African CFA Franc",
  XOF: "West African CFA Franc",
  XPF: "CFP Franc",
  YER: "Yemeni Rial",
  ZAR: "South African Rand",
  ZIG: "Zimbabwe Gold",
  ZMW: "Zambian Kwacha",
};

// Special cases that aren't a plain BASEQUOTE currency pair.
const SPECIAL_NAMES: Record<string, string> = {
  DXY: "US Dollar Index",
};

function nameFor(code: string): string {
  return CURRENCY_NAMES[code] ?? code;
}

// "EURUSD" -> "Euro - US Dollar". Falls back to the raw code for anything
// that isn't a recognizable 6-letter base+quote pair (indexes like DXY,
// or any code this map doesn't yet cover).
export function formatCurrencyPairName(code: string): string {
  if (SPECIAL_NAMES[code]) return SPECIAL_NAMES[code];
  if (code.length !== 6) return code;

  const base = code.slice(0, 3);
  const quote = code.slice(3, 6);
  return `${nameFor(base)} - ${nameFor(quote)}`;
}
