// TradingEconomics labels indices with short trading codes (US500, US30,
// GB100...) that mean nothing to Wikipedia/Investopedia search — "US500"
// matches garbage, not the S&P 500. This maps TE paths to real index names
// for display and for a much better search query. Anything not listed here
// falls back to "{code} stock market index" in TEInstrumentCard's caller.
export const INDEX_DISPLAY_NAMES: Record<string, string> = {
  "/united-states/stock-market": "S&P 500",
  "/indu:ind": "Dow Jones Industrial Average",
  "/us100:ind": "Nasdaq 100",
  "/riy:ind": "Russell 1000",
  "/japan/stock-market": "Nikkei 225",
  "/united-kingdom/stock-market": "FTSE 100",
  "/germany/stock-market": "DAX",
  "/france/stock-market": "CAC 40",
  "/italy/stock-market": "FTSE MIB",
  "/spain/stock-market": "IBEX 35",
  "/australia/stock-market": "S&P/ASX 200",
  "/china/stock-market": "Shanghai Composite",
  "/india/stock-market": "BSE SENSEX",
  "/canada/stock-market": "S&P/TSX Composite",
  "/russia/stock-market": "MOEX Russia Index",
  "/brazil/stock-market": "Bovespa",
  "/mexico/stock-market": "IPC Mexico",
  "/netherlands/stock-market": "AEX",
  "/switzerland/stock-market": "Swiss Market Index",
  "/south-africa/stock-market": "FTSE/JSE All Share",
  "/singapore/stock-market": "Straits Times Index",
  "/hong-kong/stock-market": "Hang Seng Index",
  "/new-zealand/stock-market": "NZX 50",
  "/euro-area/stock-market": "Euro Stoxx 50",
  "/turkey/stock-market": "BIST 100",
  "/sweden/stock-market": "OMX Stockholm 30",
  "/poland/stock-market": "WIG",
  "/belgium/stock-market": "BEL 20",
  "/norway/stock-market": "Oslo Stock Exchange Index",
  "/austria/stock-market": "ATX",
  "/ireland/stock-market": "ISEQ",
  "/portugal/stock-market": "PSI",
  "/argentina/stock-market": "Merval",
  "/colombia/stock-market": "COLCAP",
  "/chile/stock-market": "IGPA",
  "/stoxx:ind": "Euro Stoxx 600",
  "/mdax:ind": "MDAX",
};
